export const GET_ALL_ARTICLES_REQUEST = 'GET_ALL_ARTICLES_REQUEST'
export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS'
export const GET_ALL_ARTICLES_FAIL = 'GET_ALL_ARTICLES_FAIL'

export const CREATE_ARTICLES_REQUEST = 'CREATE_ARTICLES_REQUEST'
export const CREATE_ARTICLES_SUCCESS = 'CREATE_ARTICLES_SUCCESS'
export const CREATE_ARTICLES_FAIL = 'CREATE_ARTICLES_FAIL'
export const SET_CREATE_ARTICLE_TO_FALSE = 'SET_CREATE_ARTICLE_TO_FALSE'

export const DELETE_ARTICLES_REQUEST = 'DELETE_ARTICLES_REQUEST'
export const DELETE_ARTICLES_SUCCESS = 'DELETE_ARTICLES_SUCCESS'
export const DELETE_ARTICLES_FAIL = 'DELETE_ARTICLES_FAIL'
export const SET_DELETE_ARTICLE_TO_FALSE = 'SET_DELETE_ARTICLE_TO_FALSE'

export const GET_ONE_ARTICLE_REQUEST = 'GET_ONE_ARTICLE_REQUEST'
export const GET_ONE_ARTICLE_SUCCESS = 'GET_ONE_ARTICLE_SUCCESS'
export const GET_ONE_ARTICLE_FAIL = 'GET_ONE_ARTICLE_FAIL'

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL'
export const SET_UPDATE_ARTICLE_TO_FALSE = 'SET_CREATE_ARTICLE_TO_FALSE'
