export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_RESET = 'CART_RESET'
export const GET_POINT_RELAIS_ADDRESS = 'GET_POINT_RELAIS_ADDRESS'