export const GET_IMAGES_NAMES_REQUEST = 'GET_IMAGES_NAMES_REQUEST'
export const GET_IMAGES_NAMES_SUCCESS = 'GET_IMAGES_NAMES_SUCCESS'
export const GET_IMAGES_NAMES_FAIL = 'GET_IMAGES_NAMES_FAIL'

export const DELETE_IMAGE_DIR_REQUEST = 'DELETE_IMAGE_DIR_REQUEST'
export const DELETE_IMAGE_DIR_SUCCESS = 'DELETE_IMAGE_DIR_SUCCESS'
export const DELETE_IMAGE_DIR_FAIL = 'DELETE_IMAGE_DIR_FAIL'