export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL'

export const USER_LIST_ORDERS_REQUEST = 'USER_LIST_ORDERS_REQUEST'
export const USER_LIST_ORDERS_SUCCESS = 'USER_LIST_ORDERS_SUCCESS'
export const USER_LIST_ORDERS_FAIL = 'USER_LIST_ORDERS_FAIL'

export const GET_USER_ORDERS_REQUEST='GET_USER_ORDERS_REQUEST'
export const GET_USER_ORDERS_SUCCESS='GET_USER_ORDERS_SUCCESS'
export const GET_USER_ORDERS_FAIL='GET_USER_ORDERS_FAIL'

export const ORDERS_LIST_FAIL = 'ORDERS_LIST_FAIL'
export const ORDERS_LIST_REQUEST = 'ORDERS_LIST_REQUEST'
export const ORDERS_LIST_SUCCESS = 'ORDERS_LIST_SUCCESS'

export const GET_ORDER_FILTERS = 'GET_ORDER_FILTERS'
export const GET_FILTERED_ORDERS = 'GET_FILTERED_ORDERS'
export const UPDATE_ORDER_FILTERS = 'UPDATE_ORDER_FILTERS'