export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'
export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS ='PRODUCTS_LIST_SUCCESS'

export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS ='PRODUCT_DETAILS_SUCCESS'

export const UPDATE_PRODUCT_INFO_FAIL = 'UPDATE_PRODUCT_INFO_FAIL'
export const UPDATE_PRODUCT_INFO_REQUEST = 'UPDATE_PRODUCT_INFO_REQUEST'
export const UPDATE_PRODUCT_INFO_SUCCESS ='UPDATE_PRODUCT_INFO_SUCCESS'
export const SET_SUCCESS_TO_FALSE = 'SET_SUCCESS_TO_FALSE'

export const UPDATE_IMAGES_PRODUCT_INFO_REQUEST = 'UPDATE_IMAGES_PRODUCT_INFO_REQUEST'
export const UPDATE_IMAGES_PRODUCT_INFO_SUCCESS = 'UPDATE_IMAGES_PRODUCT_INFO_SUCCESS'
export const SET_SUCCESS_UPDATE_IMAGES_TO_FALSE = 'SET_SUCCESS_UPDATE_IMAGES_TO_FALSE'
export const UPDATE_IMAGES_PRODUCT_INFO_FAIL = 'UPDATE_IMAGES_PRODUCT_INFO_FAIL'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_IMAGES_DIR = 'DELETE_PRODUCT_IMAGES_DIR'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const SET_SUCCESS_DELETE_TO_FALSE = 'SET_SUCCESS_DELETE_TO_FALSE'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const SET_SUCCESS_CREATE_TO_FALSE = 'SET_SUCCESS_CREATE_TO_FALSE'

export const SINGLE_IMAGE_DELETE_REQUEST = 'SINGLE_IMAGE_DELETE_REQUEST'
export const SINGLE_IMAGE_DELETE_SUCCESS = 'SINGLE_IMAGE_DELETE_SUCCESS'
export const SET_SINGLE_IMAGE_DELETE_TO_FALSE = 'SET_SINGLE_IMAGE_DELETE_TO_FALSE'
export const SINGLE_IMAGE_DELETE_FAIL = 'SINGLE_IMAGE_DELETE_FAIL'