export const CREATE_SECRET_CODE_REQUEST = "CREATE_SECRET_CODE_REQUEST"
export const CREATE_SECRET_CODE_SUCCESS = "CREATE_SECRET_CODE_SUCCESS"
export const CREATE_SECRET_CODE_FAIL = "CREATE_SECRET_CODE_FAIL"