export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS'
export const USER_LOGOUT ='USER_LOGOUT'

export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS ='USER_REGISTER_SUCCESS'

export const USER_DETAILS_REQUEST ='USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS ='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL ='USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS ='USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_RESET ='USER_UPDATE_PROFILE_RESET'

export const USER_UPDATE_PASSWORD_REQUEST ='USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS ='USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL ='USER_UPDATE_PASSWORD_FAIL'

export const SEND_VALIDATION_EMAIL_REQUEST ='SEND_VALIDATION_EMAIL_REQUEST'
export const SEND_VALIDATION_EMAIL_SUCCESS ='SEND_VALIDATION_EMAIL_SUCCESS'
export const SEND_VALIDATION_EMAIL_FAIL ='SEND_VALIDATION_EMAIL_FAIL'

export const USER_UPDATE_ADDRESS_REQUEST ='USER_UPDATE_ADDRESS_REQUEST'
export const USER_UPDATE_ADDRESS_SUCCESS ='USER_UPDATE_ADDRESS_SUCCESS'
export const USER_UPDATE_ADDRESS_FAIL ='USER_UPDATE_ADDRESS_FAIL'

export const USER_UPDATE_ORDERS_REQUEST ='USER_UPDATE_ORDERS_REQUEST'
export const USER_UPDATE_ORDERS_SUCCESS ='USER_UPDATE_ORDERS_SUCCESS'
export const USER_UPDATE_ORDERS_FAIL ='USER_UPDATE_ORDERS_FAIL'

export const VALIDATE_USER_EMAIL_REQUEST ='VALIDATE_USER_EMAIL_REQUEST'
export const VALIDATE_USER_EMAIL_SUCCESS ='VALIDATE_USER_EMAIL_SUCCESS'
export const VALIDATE_USER_EMAIL_FAIL ='VALIDATE_USER_EMAIL_FAIL'

export const GET_USERS_LIST_REQUEST ='GET_USERS_LIST_REQUEST'
export const GET_USERS_LIST_SUCCESS ='GET_USERS_LIST_SUCCESS'
export const GET_USERS_LIST_FAIL='GET_USERS_LIST_FAIL'
export const GET_USERS_FILTERED = 'GET_USERS_FILTERED'
export const GET_USERS_FILTERS = 'GET_USERS_FILTERS'
export const UPDATE_USERS_FILTERS = 'UPDATE_USERS_FILTERS'
export const RESET_SEARCH_USERS = 'RESET_SEARCH_USERS'


